title: Maarouf Hatab
logo: /assets/img/Maarouf Hatab.jpg
description: Graduate Student
University of Toronto
Department of Statistical Sciences

maarouf.hatab@mail.utoronto.ca
show_downloads: false
google_analytics: false
theme: jekyll-theme-minimal
